### PR TITLE
Added Registration Page

### PR DESCRIPTION
**Pull request by AG-7219**

### CODE REVIEW

**Comment by krashish8** [comment]
@AG-7219 Just a suggestion, when clicking on Login/Signup/etc buttons, better disable the button or maybe just write somewhere "Processing..." and/or show the loading gif.

The request gets processed in the background, so there's a general habit of users to resend the request multiple times if there is no confirmation in the frontend regarding the same.

**Comment by krashish8** [comment]
image

And better change this to "Username/Email". I think this case is handled by the backend itself (check this please!!)
In such websites, it is a general tendency of users to forget the username they have used for sign up.

**Comment by krashish8** [comment]
Writing this here so that I don't forget.

Please save the token in the frontend (cookie/local storage/...) during sign-in, and delete it from the frontend during logout. If a valid token exists, then redirect any `/register/...` URL to the `/dashboard`. And vice-versa, if an invalid token exists (or a token does not exist), then redirect any `/dashboard/...` URL to `/register/login`.

**Comment by AG-7219** [comment]
> @AG-7219 Just a suggestion, when clicking on Login/Signup/etc buttons, better disable the button or maybe just write somewhere "Processing..." and/or show the loading gif.

True I should dispatch a processing toast. Should I also disable the button while the request is processing or the toast would do?

**Comment by AG-7219** [comment]
> And better change this to "Username/Email". I think this case is handled by the backend itself (check this please!!) In such websites, it is a general tendency of users to forget the username they have used for sign up.

I will have to confirm it with the backend, the api schema shows email field and not email/username, will update after confirming

**Comment by AG-7219** [comment]
> Please save the token in the frontend (cookie/local storage/...) during sign-in
Already done.
> If a valid token exists, then redirect any /register/... URL to the /dashboard. And vice-versa, if an invalid token exists (or a token does not exist), then redirect any /dashboard/... URL to /register/login.
I will add this after we complete the dashboard page.

**Comment by krashish8** [comment]
> True I should dispatch a processing toast. Should I also disable the button while the request is processing or the toast would do?

Disabling is not necessary as such. Displaying the processing message should be enough.
If the button is disabled easily (considering cases when any error re-enables the button), then you can do that.

**Comment by AG-7219** [comment]
i have made all the suggested changes except the redirect from dashboard, will do it once we finish developing the dashboard..please review and merge once done

**Review by krashish8 — APPROVED** [review]
Great work! 🤩
LGTM! :+1:

**Pull request merged**
